benitamanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^benitarecall/', include('benitarecall.urls')),
    url(r'^admin/', admin.site.urls),
]

benitarecall/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from .views import PatientFormView, PatientListView, PatientDetailView, PatientDeleteView, PatientUpdateView
from .views import CreateScheduleView, ViewScheduleView, PastRecallView, ScheduleDetailView, ScheduleUpdateView, ScheduleDeleteView

from . import views

app_name = 'benitarecall'
urlpatterns = [
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'^detail_recall(?P<pk>\d+)$', ScheduleDetailView.as_view(), name='detail_recall'),
	url(r'^update_recall(?P<pk>\d+)$', ScheduleUpdateView.as_view(), name='update_recall'),
	url(r'^delete_recall(?P<pk>\d+)$', ScheduleDeleteView.as_view(), name='delete_recall'),
	url(r'^past_recall/$', PastRecallView.as_view(), name='past_recall'),
	url(r'^view_recall/$', ViewScheduleView.as_view(), name='view_recall'),
	url(r'^create_recall/$', CreateScheduleView.as_view(), name='create_recall'),
	url(r'^patient_delete(?P<pk>\d+)$', PatientDeleteView.as_view(), name='patient_delete'),
	url(r'^patient_update(?P<pk>\d+)$', PatientUpdateView.as_view(), name='patient_update'),
	url(r'^patient_detail(?P<pk>\d+)$', PatientDetailView.as_view(), name='patient_detail'),
	url(r'^patient_list/$', PatientListView.as_view(), name='patient_list'),
	url(r'^add_patient/$', PatientFormView.as_view(), name='add_patient'),
	url(r'^$', TemplateView.as_view(template_name='benitarecall/index.html'), name='home'),
]

benitarecall/models.py
from django.db import models
from datetime import date
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError



# Create your models here.
class Patient(models.Model):
	card_number = models.CharField(unique=True, max_length=50, blank=False)
	patient_name = models.CharField(max_length=100, help_text="Title Surname Firstname", blank=False)
	sex = (
		('Male', 'Male'),
		('Female', 'Female'),
	)

	sex = models.CharField(max_length=7, choices=sex, blank=False)
	date_of_birth = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>", null=True, blank=True)
	phone_number = models.CharField(max_length=30, blank=False)
	email = models.CharField(max_length=150, blank=True)
	address = models.CharField(max_length=200, blank=True)
	occupation = models.CharField(max_length=100, blank=True)
	hmo = models.CharField("HMO", max_length=200, help_text="Name of HMO(HMO ID Number)", blank=True)


	class Meta:
		ordering = ['card_number']

	def __str__(self):
		return self.patient_name

	def get_absolute_url(self):
		return reverse('benitarecall:patient_detail', kwargs={'pk': self.pk})


class Schedule(models.Model):
	patient = models.CharField("Patient Name", max_length=100, help_text="Surname  Firstname  Othername", blank=False)
	date_of_visit = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>", blank=False)
	summary_of_visit = models.TextField(max_length=500, blank=True)
	date_of_recall = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>", blank=False)
	reason_for_recall = models.TextField(max_length=200, blank=True)

	RECALL_STATUS = (
		('On Schedule', 'On Schedule'),
		('A Reminder', 'A Reminder'),
	)

	recall_status = models.CharField(max_length=15, choices=RECALL_STATUS, blank=True, default='On Schedule')




	class Meta:
		ordering = ['date_of_recall']
		

	def __str__(self):
		return self.patient

	def get_absolute_url(self):
		return reverse('benitarecall:detail_recall', kwargs={'pk': self.pk})

	def clean(self):
		date_of_recall = self.date_of_recall

		if date_of_recall < date.today():
			raise ValidationError('You cannot schedule a recall for the past. Please check your date')


	
	

benitarecall/views.py
from django.conf import settings
from django.db.models import Q
from datetime import date 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy 
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import FormView
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.shortcuts import render
from benitarecall.models import Patient
from benitarecall.models import Schedule


# Create your views here.

class PatientFormView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

	model = Patient
	template_name = 'benitarecall/add_patient.html'
	fields = ['card_number', 'patient_name', 'sex', 'date_of_birth', 'phone_number', 'email', 'address', 'occupation', 'hmo']
	success_url = reverse_lazy('benitarecall:add_patient')
	success_message = 'Patient successfully added'


class PatientListView(LoginRequiredMixin, ListView):

	model = Patient
	template_name = 'benitarecall/list_patient.html'
	context_object_name = 'patients'
	paginate_by = 20

	def get_queryset(self, *args, **kwargs):
		queryset_list = Patient.objects.all()
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(card_number__icontains=query)|
				Q(patient_name__icontains=query)
				).distinct()
		return queryset_list



class PatientDetailView(DetailView):

	model = Patient
	template_name = 'benitarecall/detail_patient.html'
	context_object_name = 'patients'

class PatientDeleteView(SuccessMessageMixin, DeleteView):

	model = Patient
	template_name = 'benitarecall/delete_patient.html'
	success_url = reverse_lazy('benitarecall:patient_list')


class PatientUpdateView(SuccessMessageMixin, UpdateView):

	model = Patient
	template_name = 'benitarecall/update_patient.html'
	fields = ['card_number', 'patient_name', 'sex', 'date_of_birth', 'phone_number', 'email', 'address', 'occupation', 'hmo']
	success_url = reverse_lazy('benitarecall:patient_list') 
	
class CreateScheduleView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    #Powers a form to create a new recall

	model = Schedule
	template_name = 'benitarecall/create_recall.html'
	fields = ['patient', 'date_of_visit', 'summary_of_visit', 'date_of_recall', 'reason_for_recall', 'recall_status']
	success_url = reverse_lazy('benitarecall:create_recall')
	success_message = 'Recall successfully created'


class ViewScheduleView(LoginRequiredMixin, ListView):

	#Shows users a list of appointments.  

	model = Schedule
	template_name = 'benitarecall/view_recall.html'
	context_object_name = 'view_recall' 
	paginate_by = 20
	queryset_list = Schedule.objects.exclude(date_of_recall__lt=date.today())

	
	def get_queryset(self, *args, **kwargs):
		queryset_list = Schedule.objects.exclude(date_of_recall__lt=date.today())
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(date_of_recall__icontains=query)|
				Q(patient__icontains=query)
				).distinct()
		return queryset_list


class PastRecallView(ListView):

	model = Schedule
	template_name = 'benitarecall/past_recall.html'
	context_object_name = 'past_recall'
	paginate_by = 20
	queryset_list = Schedule.objects.filter(date_of_recall__lt=date.today())


	def get_queryset(self, *args, **kwargs):
		queryset_list = Schedule.objects.filter(date_of_recall__lt=date.today())
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(date_of_recall__icontains=query)|
				Q(patient__icontains=query)
				).distinct()
		return queryset_list


	
class ScheduleDetailView(DetailView):

	#Shows users a single appointment

	model = Schedule
	template_name = 'benitarecall/detail_recall.html'
	context_object_name = 'schedule'

class ScheduleUpdateView(SuccessMessageMixin, UpdateView):
	#powers a form to edit existing recall

	model = Schedule
	template_name = 'benitarecall/schedule_form.html'
	fields = ['patient', 'date_of_visit', 'summary_of_visit', 'date_of_recall', 'reason_for_recall', 'recall_status']
	success_url = reverse_lazy('benitarecall:view_recall')
	success_message = 'Recall successfully updated'



class ScheduleDeleteView(SuccessMessageMixin, DeleteView):
	#prompts user to confirm deletion of a recall

	model = Schedule
	success_url = reverse_lazy('benitarecall:view_recall')

benitarecall/templates/benitarecall/add_patient.html
{% extends 'benitarecall/layout.html' %}

{% load bootstrap %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block content %}

<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Add Patient</b></h1>
			</div>
		</div>
	</div>
	<br>
</div><br>

<div class="container">
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
	{% if messages %}
	{% bootstrap_javascript jquery=1 %}
	{% bootstrap_messages %}
	{% endif %}
	<form method="POST" action="{% url 'benitarecall:add_patient' %}" class="form">
		{{ form|bootstrap }}
		{% csrf_token %}
		<input type="submit" value="Add Patient" class="btn btn-success"> 
	</form>
</div>
</div>
</div><br>

{% endblock %}

benitarecall/templates/benitarecall/create_recall.html
{% extends 'benitarecall/layout.html' %}

{% load bootstrap3 %}
{% load bootstrap %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block title %}Create Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Create Recall</b></h1>
			<h3>Today is {% now "D d M Y" %}: {% now "H:i" %}</h3>
			</div>
		</div>
	</div>
	<br>
</div>
			

<div class="container"><br>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" class="form-group">
			{% if messages %}
			{% bootstrap_javascript jquery=1 %}
			{% bootstrap_messages %}
			{% endif %}
			<form method="POST" action="{% url 'benitarecall:create_recall' %}" class="form">
			{{ form|bootstrap }}
			{% csrf_token %}
			<input type="submit" value="Create" class="btn btn-success"> 
			</form>
		</div>
	</div>
</div>
{% endblock %}

benitarecall/templates/benitarecall/delete_patient.html
{% extends 'benitarecall/layout.html' %}

{% load bootstrap3 %}


{% block title %}Delete Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Delete Patient</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-6">
			<form method="POST" action="">
			{% csrf_token %}
			<h3>Are you sure you want to delete the record for "{{ patient }}"?</h3>
			{% buttons %}
		    	<button type="submit" class="btn btn-danger">
		      		{% bootstrap_icon "remove" %} Delete
		    	</button>
		  	{% endbuttons %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

benitarecall/templates/benitarecall/detail_patient.html
{% extends 'benitarecall/layout.html' %}


{% block title %}Patient Detail | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
  <br>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-xs-12">
      <h1><b>Patient Detail</b></h1>
      </div>
    </div>
  </div>
  <br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Card Number</h3>
  </div>
  <div class="panel-body">
    {{ patients.card_number }} 
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Name</h3>
  </div>
  <div class="panel-body">
    {{ patients.patient_name }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Sex</h3>
  </div>
  <div class="panel-body">
    {{ patients.sex }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Date of Birth</h3>
  </div>
  <div class="panel-body">
    {{ patients.date_of_birth }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Phone Number</h3>
  </div>
  <div class="panel-body">
    {{ patients.phone_number }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Email</h3>
  </div>
  <div class="panel-body">
    {{ patients.email }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Address</h3>
  </div>
  <div class="panel-body">
    {{ patients.address }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Occupation</h3>
  </div>
  <div class="panel-body">
    {{ patients.occupation }}
  </div>
 </div>
 <div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Health Management Organisation</h3>
  </div>
  <div class="panel-body">
    {{ patients.hmo }}
  </div>
 </div>
 </div>
</div>
</div>
  
{% endblock %}

benitarecall/templates/benitarecall/layout.html
benita<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width,initial-scale=1" name=viewport>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/benitarecall.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Spectral" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   <nav style="background:#01092B !important" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-slide-dropdown">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'benitarecall:home' %}">Benita Recall Manager</a>
        </div>
         <div class="collapse navbar-collapse" id="bs-slide-dropdown">
              <ul class="nav navbar-nav navbar-right">
                <li role="presentation" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Patient<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       <li><a href="{% url 'benitarecall:add_patient' %}">Add patient</a></li>
                       <li><a href="{% url 'benitarecall:patient_list' %}">View patient</a></li> 
                    </ul>
                </li>
                 <li role="presentation" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Recall<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       <li><a href="{% url 'benitarecall:create_recall' %}">Create recall</a></li>
                       <li><a href="{% url 'benitarecall:view_recall' %}">View upcoming recall</a></li>
                       <li><a href="{% url 'benitarecall:past_recall' %}">View past recall</a></li>  
                    </ul>
                </li>
              </ul>
        </div>
        </div>
    </nav>



    {% block content %}{% endblock %}

    <hr>

    <div class="container">
       <footer>
        <p>&copy; 2017 Practice Companion Nigeria</p>
      </footer>
    </div> <!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

benitarecall/templates/benitarecall/list_patient.html
{% extends 'benitarecall/layout.html' %}



{% block content %}

<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Patients</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Card Number or Name" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Card Number</span></th>
        <th><span>Name</span></th>
        <th><span>Phone</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for patient in patients %}  
      <tr>
        <td>{{ patient.card_number }}</td>
        <td><a href="{{ patient.get_absolute_url }}">{{ patient.patient_name }}</a></td>
        <td>{{ patient.phone_number }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'benitarecall:patient_update' patient.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'benitarecall:patient_delete' patient.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
{% endif %}
</div>

{% endblock %}

benitarecall/templates/benitarecall/past_recall.html
{% extends 'benitarecall/layout.html' %}


{% block title %}View Recalls | {{ block.super }}{% endblock %}

{% block content %}
<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Past Recalls</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Name or Date of Recall(YYYY-MM-DD)" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-10">
  {% if not past_recall %}
    <p><strong>You Have No Recalls.</strong> Why not <a href="{% url 'benitarecall:create_recall' %}">create one?</a></p>
  {% endif %}
</div>
</div>
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Name</span></th>
        <th><span>Recall Date</span></th>
        <th><span>Recall Status</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for schedule in past_recall|dictsort:"date_of_visit" %}   
    
      <tr>
        <td><a href="{{ schedule.get_absolute_url }}">{{ schedule.patient }}</a></td>
        <td>{{ schedule.date_of_recall }}</td>
        <td>{{ schedule.recall_status }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'benitarecall:update_recall' schedule.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'benitarecall:delete_recall' schedule.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>

    {% endfor %}
    </tbody>
  </table>

 {% if is_paginated %}
   
    
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  
  {% endif %}
  </div>
  </div>
  </div>
 </div> 
{% endblock %}

benitarecall/templates/benitarecall/schedule_confirm_delete.html
{% extends 'benitarecall/layout.html' %}

{% load bootstrap3 %}


{% block title %}Delete Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Delete Recall</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-6">
			<form method="POST" action="">
			{% csrf_token %}
			<h3>Are you sure you want to delete a recall for "{{ schedule }}"?</h3>
			{% buttons %}
		    	<button type="submit" class="btn btn-danger">
		      		{% bootstrap_icon "remove" %} Delete
		    	</button>
		  	{% endbuttons %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

benitarecall/templates/benitarecall/view_recall.html
{% extends 'benitarecall/layout.html' %}


{% block title %}View Recalls | {{ block.super }}{% endblock %}

{% block content %}
<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Recalls</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Name or Date of Recall(YYYY-MM-DD)" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-10">
  {% if not view_recall %}
    <p><strong>You Have No Recalls.</strong> Why not <a href="{% url 'benitarecall:create_recall' %}">create one?</a></p>
  {% endif %}
</div>
</div>
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Name</span></th>
        <th><span>Recall Date</span></th>
        <th><span>Recall Status</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for schedule in view_recall|dictsort:"date_of_recall" %}  
      <tr>
        <td><a href="{{ schedule.get_absolute_url }}">{{ schedule.patient }}</a></td>
        <td>{{ schedule.date_of_recall }}</td>
        <td>{{ schedule.recall_status }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'benitarecall:update_recall' schedule.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'benitarecall:delete_recall' schedule.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

 {% if is_paginated %}
 
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>

  {% endif %}
  </div>
  </div>
  </div>
 </div> 
{% endblock %}